DEFECT_SEQUENCE_MAP = {
    1: 'Misaligned or Missing Balls or Columns',
    2: 'No ESD Bags for ESD Sensitive Devices',
    3: 'Lead Re-attachment',
    4: 'Defect Name',
    5: 'Oxidation or Corrosion',
    6: 'Die Damage or Extraneous Markings',
    7: 'Delamination',
    8: 'Mechanical Interfaces Intermetallic Growth',
    9: 'Improper Textures',
    10: 'Pin Marker Filled or Missing',
    11: 'Surface Impurities',
    12: 'Fine or Gross Leak (Hermetic)',
    13: 'Threshold Variation',
    14: 'Package Contamination',
    15: 'Invalid OCM or OEM Shipping Labels',
    16: 'Parasitic Transistors',
    17: 'Invalid Lot Code',
    18: 'Tooling Marks',
    19: 'Package Mold Variations',
    20: 'No Moisture Protection for Moisture Sensitive Devices',
    21: 'Incorrect Dimensions or Weight',
    22: 'TDDB',
    23: 'Markings',
    24: 'Dirty Cavities',
    25: 'Surface Passivation and Corrosion',
    26: 'Contamination',
    27: 'Abnormal Package Conditions',
    28: 'Resistive Open or Short',
    29: 'Sanding or Grinding Marks',
    30: 'Incorrect Dimensions',
    31: 'Resurfacing or Blacktopping',
    32: 'Poor Connection',
    33: 'Out-of-Spec Leakage Current',
    34: 'Crystal Imperfection',
    35: 'Multiple Date Codes Within Lot',
    36: 'Mechanical Interfaces Fatigue',
    37: 'Invalid OCM or OEM Packaging',
    38: 'Wrong Die',
    39: 'Color Variations or Fade',
    40: 'Improper Materials (Seals,Epoxies, Dielectrics, etc)',
    41: 'Invalid Markings',
    42: 'Package Damage',
    43: 'Incorrect Temp Profile',
    44: 'Poor or Inconsistent Die Attach',
    45: 'Poor or Inconsistent Lead Dress or Lead Frame',
    46: 'Oxide Breakdown',
    47: 'Re-Worked Wire Bonds',
    48: 'Missing Wires',
    49: 'Bond fPull Strength',
    50: 'Color Variations',
    51: 'Reworked',
    52: 'Ghost Markings',
    53: 'Missing Contact Windows',
    54: 'Distorted Non-uniform Balls or Columns',
    55: 'Wrong Materials',
    56: 'Missing Die',
    57: 'Fine Cracks',
    58: 'Dents, Damaged, or Bent',
    59: 'Burned Markings',
    60: 'Part Orientation within Packaging',
    61: 'Missing or Forged Paperwork',
    62: 'Extraneous Markings',
    63: 'Broken Wires',
    64: 'Delay Defects',
    65: 'Gross Cracks',
    66: 'Improper Die Markings',
    67: 'Misaligned Window'
}

a = {'ML1': 'Dents or Damaged or Bent',
     'ML2': 'Reworked',
     'ML3': 'Incorrect Dimensions',
     'ML4': 'Wrong Materials',
     'ML5': 'Color Variations',
     'ML6': 'Tooling Marks',
     'ML7': 'Misaligned or missing Balls or Columns',
     'ML8': 'Distorted or Non-Uniform Balls or Columns',
     'ML9': 'Lead Reattachment',
     'MP1': 'Sanding or Gringing Marks',
     'MP2': 'Markings',
     'MP3': 'Burned Markings',
     'MP4': 'Ghost Markings',
     'MP5': 'Color Variations or Fade',
     'MP6': 'Improper Textures',
     'MP7': 'Extraneous Markings',
     'MP8': 'Dirty Cavities',
     'MP9': 'Incorrect Dimensions or Weight',
     'MP10': 'Fine or Gross Leak (Hermatic)',
     'MP11': 'Package Mold Variations',
     'MP12': 'Package Damage',
     'MP13': 'Resurfacing or blacktopping',
     'MP14': 'Pin 1 marker filled or missing',
     'MB1': 'Missing Wires',
     'MB2': 'Poor Connection',
     'MB3': 'Broken Wires',
     'MB4': 'Poor Inconsistent Lead Dress or Lead Frame',
     'MB5': 'Reworked Wire Bonds',
     'MB6': 'Bond Pull Strength',
     'MD1': 'Missing Die',
     'MD2': 'Wrong Die',
     'MD3': 'Delamination',
     'MD4': 'Gross Cracks',
     'MD5': 'Improper Die Markings',
     'MD6': 'Die Damage or Extraneous Markings',
     'MD7': 'Poor or Inconsistent Die Attach',
     'NL1': 'Lead or Balls Contamination',
     'NL2': 'Oxidation or Corrosion',
     'NP1': 'Abnormal Package Conditions',
     'NP2': 'Package Contamination'}
